version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /api
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /api
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /libs/docs
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /libs/external
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /libs/server
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /libs/typescript
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /libs/util
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /onboarding
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /onboarding
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /panel
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /panel
    schedule:
      interval: daily
  - package-ecosystem: terraform
    directory: /terraform
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /.github/workflow
    schedule:
      interval: daily
