version: 2
updates:
  - package-ecosystem: npm
    reviewers:
      - kashw2
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: docker
    reviewers:
      - kashw2
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: terraform
    reviewers:
      - kashw2
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    reviewers:
      - kashw2
    directory: /
    schedule:
      interval: daily
