name: GitHub Pages

on:
  workflow_dispatch:
  push:
    paths:
      - libs/**
    branches:
      - main

jobs:
  publish:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: npm auth
        run: |
          npm config set @kashw2:registry https://npm.pkg.github.com/
          npm config set //npm.pkg.github.com/:_authToken=${{ secrets.NPM_PACKAGE_TOKEN }}
          npm config set registry https://registry.npmjs.org/

      - name: install globals
        run: npm install -g lerna rimraf typescript

      - name: npm install
        run: |
          lerna exec npm install --scope=fleet-of-the-faithful-knights
          lerna exec npm install --scope=@ffk/docs

      - name: publish
        run: lerna run doc:ci --scope=@ffk/docs