name: Utility Library

on:
  workflow_dispatch:
  pull_request:
    paths:
      - package.json
      - libs/util/**
    branches:
      - main

jobs:
  test-lib-util:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: npm auth
        run: |
          npm config set @kashw2:registry https://npm.pkg.github.com/
          npm config set //npm.pkg.github.com/:_authToken=${{ secrets.NPM_PACKAGE_TOKEN }}
          npm config set registry https://registry.npmjs.org/

      - name: install globals
        run: npm install -g lerna

      - name: npm install
        run: |
          lerna exec npm install --scope=fleet-of-the-faithful-knights
          lerna exec npm install --scope=@kashw2/lib-util

      - name: test util
        run: lerna run test --scope=@kashw2/lib-util

      - name: generate coverage
        run: |
          lerna run cov:ci --scope=@kashw2/lib-util

      - name: setup codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: libs/util
  e2e-lib-util:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: npm auth
        run: |
          npm config set @kashw2:registry https://npm.pkg.github.com/
          npm config set //npm.pkg.github.com/:_authToken=${{ secrets.NPM_PACKAGE_TOKEN }}
          npm config set registry https://registry.npmjs.org/

      - name: install globals
        run: npm install -g lerna rimraf typescript

      - name: npm install
        run: |
          lerna exec npm install --scope=fleet-of-the-faithful-knights
          lerna exec npm install --scope=@kashw2/lib-util
          lerna exec npm install --scope=@ffk/lib-util-e2e

      - name: build
        run: lerna run build --scope=@kashw2/lib-util

      - name: e2e
        run: lerna run build --scope=@ffk/lib-util-e2e
  build-lib-util:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: npm auth
        run: |
          npm config set @kashw2:registry https://npm.pkg.github.com/
          npm config set //npm.pkg.github.com/:_authToken=${{ secrets.NPM_PACKAGE_TOKEN }}
          npm config set registry https://registry.npmjs.org/

      - name: install globals
        run: npm install -g lerna rimraf typescript

      - name: npm install
        run: |
          lerna exec npm install --scope=fleet-of-the-faithful-knights
          lerna exec npm install --scope=@kashw2/lib-util

      - name: build
        run: lerna run build --scope=@kashw2/lib-util
  publish:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: npm auth
        run: |
          npm config set @kashw2:registry https://npm.pkg.github.com/
          npm config set //npm.pkg.github.com/:_authToken=${{ secrets.NPM_PACKAGE_TOKEN }}
          npm config set registry https://registry.npmjs.org/

      - name: install globals
        run: npm install -g lerna rimraf typescript

      - name: npm install
        run: |
          lerna exec npm install --scope=fleet-of-the-faithful-knights
          lerna exec npm install --scope=@kashw2/lib-util

      - name: build
        run: lerna run build --scope=@kashw2/lib-util

      - name: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_PACKAGE_TOKEN }}
          package: ./libs/util/package.json
          registry: https://npm.pkg.github.com/