name: Panel

on:
  workflow_dispatch:
  pull_request:
    paths:
      - package.json
      - panel/**
    branches:
      - main
  push:
    paths:
      - panel/**
    branches:
      - main

jobs:
  build:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: npm auth
        run: |
          npm config set @kashw2:registry https://npm.pkg.github.com/
          npm config set //npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}
          npm config set registry https://registry.npmjs.org/

      - name: install globals
        run: npm install -g lerna @angular/cli &> /dev/null

      - name: npm install
        run: |
          lerna exec npm ci --scope=fleet-of-the-faithful-knights -- --force
          lerna exec npm ci --scope=@ffk/panel -- --force

      - name: build panel
        run: lerna run build --scope=@ffk/panel
  deploy:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: npm auth
        run: |
          npm config set @kashw2:registry https://npm.pkg.github.com/
          npm config set //npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}
          npm config set registry https://registry.npmjs.org/

      - name: install globals
        run: npm install -g lerna @angular/cli &> /dev/null

      - name: npm install
        run: |
          lerna exec npm ci --scope=fleet-of-the-faithful-knights -- --force
          lerna exec npm ci --scope=@ffk/panel -- --force

      - name: build panel
        run: lerna run build:prod --scope=@ffk/panel
        working-directory: panel

      - name: deploy
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - run: |
          docker build -t ghcr.io/kashw2/panel.faithfulknights.com:${{ github.sha }} -t ghcr.io/kashw2/panel.faithfulknights.com:latest -f Dockerfile .
          docker push ghcr.io/kashw2/panel.faithfulknights.com:${{ github.sha }}
          docker push ghcr.io/kashw2/panel.faithfulknights.com:latest
        working-directory: panel

